//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesKaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Id_Type { get; set; }
        public int Id_Size { get; set; }
        public int Price { get; set; }
        public int Id_Magazine { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Size Size { get; set; }
        public virtual TypeClothes TypeClothes { get; set; }
        public virtual Magazine Magazine { get; set; }
    }
}
