//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesKaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlimCloEntities : DbContext
    {
        private static KlimCloEntities _context;
        public KlimCloEntities()
            : base("name=KlimCloEntities")
        {
        }
        public static KlimCloEntities GetContext()
        {
            if (_context == null)
                _context = new KlimCloEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clothes> Clothes { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeClothes> TypeClothes { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Magazine> Magazine { get; set; }
    }
}
